CRITICAL - 2022-12-06 00:53:06 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 00:53:08 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 00:53:12 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 00:53:14 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 00:53:18 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 00:53:21 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 00:53:24 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 01:05:51 --> Call to undefined function App\Controllers\V1\Trackless\liveapi()
in APPPATH/Controllers/V1/Trackless/Currency.php on line 50.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Trackless\Currency->currencyStatus()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Trackless\Currency))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-06 01:12:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'piggybankservice_bank'@'localhost' to database 'piggybankservice_trackless' in /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('localhost', 'piggybankservic...', '%t=dJkm_+7W1', 'piggybankservic...', 3306, '', 0)
#1 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/piggybankservice/api/api.tracklessbank.com/app/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM b...', Array)
#4 /home/piggybankservice/api/api.tracklessbank.com/app/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9a...')
#5 /home/piggybankservice/api/api.tracklessbank.com/app/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9a...')
#6 /home/piggybankservice/api/api.tracklessbank.com/system/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/co...', 'before')
#8 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/piggybankservice/api/api.tracklessbank.com/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database 'piggybankservice_trackless' in /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/piggybankservice/api/api.tracklessbank.com/app/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM b...', Array)
#3 /home/piggybankservice/api/api.tracklessbank.com/app/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9a...')
#4 /home/piggybankservice/api/api.tracklessbank.com/app/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9a...')
#5 /home/piggybankservice/api/api.tracklessbank.com/system/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#6 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/co...', 'before')
#7 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /home/piggybankservice/api/api.tracklessbank.com/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-06 01:12:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database 'piggybankservice_trackless'
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM bankmember WHERE apikey=?', [...])
 3 APPPATH/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9aqfWVREKvNzKOUh5ei5DQPHXCMkIluGCwkXu')
 4 APPPATH/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9aqfWVREKvNzKOUh5ei5DQPHXCMkIluGCwkXu')
 5 SYSTEMPATH/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 6 SYSTEMPATH/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/cost/getWiseCost', 'before')
 7 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-06 01:12:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'piggybankservice_bank'@'localhost' to database 'piggybankservice_trackless' in /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('localhost', 'piggybankservic...', '%t=dJkm_+7W1', 'piggybankservic...', 3306, '', 0)
#1 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/piggybankservice/api/api.tracklessbank.com/app/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM b...', Array)
#4 /home/piggybankservice/api/api.tracklessbank.com/app/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9a...')
#5 /home/piggybankservice/api/api.tracklessbank.com/app/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9a...')
#6 /home/piggybankservice/api/api.tracklessbank.com/system/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/cu...', 'before')
#8 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/piggybankservice/api/api.tracklessbank.com/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database 'piggybankservice_trackless' in /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/piggybankservice/api/api.tracklessbank.com/app/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM b...', Array)
#3 /home/piggybankservice/api/api.tracklessbank.com/app/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9a...')
#4 /home/piggybankservice/api/api.tracklessbank.com/app/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9a...')
#5 /home/piggybankservice/api/api.tracklessbank.com/system/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#6 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/cu...', 'before')
#7 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /home/piggybankservice/api/api.tracklessbank.com/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-06 01:12:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database 'piggybankservice_trackless'
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM bankmember WHERE apikey=?', [...])
 3 APPPATH/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9aqfWVREKvNzKOUh5ei5DQPHXCMkIluGCwkXu')
 4 APPPATH/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9aqfWVREKvNzKOUh5ei5DQPHXCMkIluGCwkXu')
 5 SYSTEMPATH/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 6 SYSTEMPATH/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/currency/getAllCurrency', 'before')
 7 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-06 01:12:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'piggybankservice_bank'@'localhost' to database 'piggybankservice_trackless' in /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('localhost', 'piggybankservic...', '%t=dJkm_+7W1', 'piggybankservic...', 3306, '', 0)
#1 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/piggybankservice/api/api.tracklessbank.com/app/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM b...', Array)
#4 /home/piggybankservice/api/api.tracklessbank.com/app/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9a...')
#5 /home/piggybankservice/api/api.tracklessbank.com/app/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9a...')
#6 /home/piggybankservice/api/api.tracklessbank.com/system/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/cu...', 'before')
#8 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/piggybankservice/api/api.tracklessbank.com/public/index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database 'piggybankservice_trackless' in /home/piggybankservice/api/api.tracklessbank.com/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/piggybankservice/api/api.tracklessbank.com/system/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/piggybankservice/api/api.tracklessbank.com/app/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM b...', Array)
#3 /home/piggybankservice/api/api.tracklessbank.com/app/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9a...')
#4 /home/piggybankservice/api/api.tracklessbank.com/app/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9a...')
#5 /home/piggybankservice/api/api.tracklessbank.com/system/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#6 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/cu...', 'before')
#7 /home/piggybankservice/api/api.tracklessbank.com/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /home/piggybankservice/api/api.tracklessbank.com/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-06 01:12:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database 'piggybankservice_trackless'
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/ValidateToken.php(21): CodeIgniter\Database\BaseConnection->query('SELECT * FROM bankmember WHERE apikey=?', [...])
 3 APPPATH/Helpers/preapi_helper.php(13): App\Models\ValidateToken->checkAPIkey('pPaqjxUmeiwXb9aqfWVREKvNzKOUh5ei5DQPHXCMkIluGCwkXu')
 4 APPPATH/Filters/FilterApi.php(19): validateKey('pPaqjxUmeiwXb9aqfWVREKvNzKOUh5ei5DQPHXCMkIluGCwkXu')
 5 SYSTEMPATH/Filters/Filters.php(173): App\Filters\FilterApi->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 6 SYSTEMPATH/CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('v1/trackless/currency/getAllCurrency', 'before')
 7 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 23:38:00 --> Call to undefined function App\Controllers\V1\Member\sandbox()
in APPPATH/Controllers/V1/Member/Swap.php on line 212.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Member\Swap->swapCurrency()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Member\Swap))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 23:39:24 --> Call to undefined function App\Controllers\V1\Member\sandbox()
in APPPATH/Controllers/V1/Member/Swap.php on line 212.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Member\Swap->swapCurrency()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Member\Swap))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-06 23:40:09 --> Call to undefined function App\Controllers\V1\Member\sandbox()
in APPPATH/Controllers/V1/Member/Swap.php on line 212.
 1 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\V1\Member\Swap->swapCurrency()
 2 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\V1\Member\Swap))
 3 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
